[package]
name = "aporia"
version = "0.1.1"
edition = "2021"
description = "A flexible random number generation library"
license = "MIT"
repository = "https://github.com/SkuldNorniern/aporia"

[lib]
name = "aporia"
path = "src/lib.rs"

[dependencies]
